apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-deploy
  labels:
    app: entity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entity-service
  template:
    metadata:
      labels:
        app: entity-service
    spec:
      containers:
        - name: entity-container
          image: "entity-service:latest"
          imagePullPolicy: Never
          env:
          - name: DB_HOST
            value: entity-db-postgresql.svc
          - name: DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: entity-db-postgresql
                key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: entity-service
  name: entity-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: entity-service
  type: ClusterIP
status:
  loadBalancer: {}
